server:
  port: 1001
spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      routes:
        - id: livy-service
          uri: lb://livy-service
          predicates:
            - Path=/livy-service/**
          filters:
            - StripPrefix=1
            - Auth=true



