export const SimpleTrain = [
    {"id":1,"age":10,"gender":"male","score":35},
    {"id":2,"age":12,"gender":"female","score":36},
    {"id":3,"age":14,"gender":"male","score":37},
    {"id":4,"age":null ,"gender":"male","score":38},
    {"id":5,"age":18,"gender":"female","score":null},
    {"id":6,"age":20,"gender":"male","score":40},
    {"id":7,"age":22,"gender":"male","score":41},
    {"id":8,"age":24,"gender":"female","score":null},
    {"id":9,"age":26,"gender":"male","score":43},
    {"id":10,"age":null,"gender":"male","score":44},
    {"id":11,"age":30,"gender":"female","score":45},
    {"id":12,"age":32,"gender":"male","score":null},
    {"id":13,"age":34,"gender":"male","score":47},
    {"id":14,"age":36,"gender":"female","score":48},
    {"id":15,"age":38,"gender":"male","score":49},
    {"id":16,"age":30,"gender":"male","score":50},
    {"id":17,"age":null,"gender":"female","score":51},
    {"id":18,"age":44,"gender":"male","score":52},
    {"id":19,"age":45,"gender":"male","score":53},
    {"id":20,"age":46,"gender":"female","score":54},
    {"id":21,"age":null,"gender":"male","score":55},
    {"id":22,"age":48,"gender":"male","score":56},
    {"id":23,"age":49,"gender":"female","score":57}
    ]