export const data = [
    {"PassengerId":"1","Survived":"0","Pclass":"3","Name":"Braund, Mr. Owen Harris","Sex":"male","Age":"22","SibSp":"1","Parch":"0","Ticket":"A/5 21171","Fare":"7.25","Cabin":"","Embarked":"S"},
    {"PassengerId":"2","Survived":"1","Pclass":"1","Name":"Cumings, Mrs. John Bradley (Florence Briggs Thayer)","Sex":"female","Age":"38","SibSp":"1","Parch":"0","Ticket":"PC 17599","Fare":"71.2833","Cabin":"C85","Embarked":"C"},
    {"PassengerId":"3","Survived":"1","Pclass":"3","Name":"Heikkinen, Miss. Laina","Sex":"female","Age":"26","SibSp":"0","Parch":"0","Ticket":"STON/O2. 3101282","Fare":"7.925","Cabin":"","Embarked":"S"},
    {"PassengerId":"4","Survived":"1","Pclass":"1","Name":"Futrelle, Mrs. Jacques Heath (Lily May Peel)","Sex":"female","Age":"35","SibSp":"1","Parch":"0","Ticket":"113803","Fare":"53.1","Cabin":"C123","Embarked":"S"},
    {"PassengerId":"5","Survived":"0","Pclass":"3","Name":"Allen, Mr. William Henry","Sex":"male","Age":"35","SibSp":"0","Parch":"0","Ticket":"373450","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"6","Survived":"0","Pclass":"3","Name":"Moran, Mr. James","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"330877","Fare":"8.4583","Cabin":"","Embarked":"Q"},
    {"PassengerId":"7","Survived":"0","Pclass":"1","Name":"McCarthy, Mr. Timothy J","Sex":"male","Age":"54","SibSp":"0","Parch":"0","Ticket":"17463","Fare":"51.8625","Cabin":"E46","Embarked":"S"},
    {"PassengerId":"8","Survived":"0","Pclass":"3","Name":"Palsson, Master. Gosta Leonard","Sex":"male","Age":"2","SibSp":"3","Parch":"1","Ticket":"349909","Fare":"21.075","Cabin":"","Embarked":"S"},
    {"PassengerId":"9","Survived":"1","Pclass":"3","Name":"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)","Sex":"female","Age":"27","SibSp":"0","Parch":"2","Ticket":"347742","Fare":"11.1333","Cabin":"","Embarked":"S"},
    {"PassengerId":"10","Survived":"1","Pclass":"2","Name":"Nasser, Mrs. Nicholas (Adele Achem)","Sex":"female","Age":"14","SibSp":"1","Parch":"0","Ticket":"237736","Fare":"30.0708","Cabin":"","Embarked":"C"},
    {"PassengerId":"11","Survived":"1","Pclass":"3","Name":"Sandstrom, Miss. Marguerite Rut","Sex":"female","Age":"4","SibSp":"1","Parch":"1","Ticket":"PP 9549","Fare":"16.7","Cabin":"G6","Embarked":"S"},
    {"PassengerId":"12","Survived":"1","Pclass":"1","Name":"Bonnell, Miss. Elizabeth","Sex":"female","Age":"58","SibSp":"0","Parch":"0","Ticket":"113783","Fare":"26.55","Cabin":"C103","Embarked":"S"},
    {"PassengerId":"13","Survived":"0","Pclass":"3","Name":"Saundercock, Mr. William Henry","Sex":"male","Age":"20","SibSp":"0","Parch":"0","Ticket":"A/5. 2151","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"14","Survived":"0","Pclass":"3","Name":"Andersson, Mr. Anders Johan","Sex":"male","Age":"39","SibSp":"1","Parch":"5","Ticket":"347082","Fare":"31.275","Cabin":"","Embarked":"S"},
    {"PassengerId":"15","Survived":"0","Pclass":"3","Name":"Vestrom, Miss. Hulda Amanda Adolfina","Sex":"female","Age":"14","SibSp":"0","Parch":"0","Ticket":"350406","Fare":"7.8542","Cabin":"","Embarked":"S"},
    {"PassengerId":"16","Survived":"1","Pclass":"2","Name":"Hewlett, Mrs. (Mary D Kingcome) ","Sex":"female","Age":"55","SibSp":"0","Parch":"0","Ticket":"248706","Fare":"16","Cabin":"","Embarked":"S"},
    {"PassengerId":"17","Survived":"0","Pclass":"3","Name":"Rice, Master. Eugene","Sex":"male","Age":"2","SibSp":"4","Parch":"1","Ticket":"382652","Fare":"29.125","Cabin":"","Embarked":"Q"},
    {"PassengerId":"18","Survived":"1","Pclass":"2","Name":"Williams, Mr. Charles Eugene","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"244373","Fare":"13","Cabin":"","Embarked":"S"},
    {"PassengerId":"19","Survived":"0","Pclass":"3","Name":"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)","Sex":"female","Age":"31","SibSp":"1","Parch":"0","Ticket":"345763","Fare":"18","Cabin":"","Embarked":"S"},
    {"PassengerId":"20","Survived":"1","Pclass":"3","Name":"Masselmani, Mrs. Fatima","Sex":"female","Age":"","SibSp":"0","Parch":"0","Ticket":"2649","Fare":"7.225","Cabin":"","Embarked":"C"},
    {"PassengerId":"21","Survived":"0","Pclass":"2","Name":"Fynney, Mr. Joseph J","Sex":"male","Age":"35","SibSp":"0","Parch":"0","Ticket":"239865","Fare":"26","Cabin":"","Embarked":"S"},
    {"PassengerId":"22","Survived":"1","Pclass":"2","Name":"Beesley, Mr. Lawrence","Sex":"male","Age":"34","SibSp":"0","Parch":"0","Ticket":"248698","Fare":"13","Cabin":"D56","Embarked":"S"},
    {"PassengerId":"24","Survived":"1","Pclass":"1","Name":"Sloper, Mr. William Thompson","Sex":"male","Age":"28","SibSp":"0","Parch":"0","Ticket":"113788","Fare":"35.5","Cabin":"A6","Embarked":"S"},
    {"PassengerId":"25","Survived":"0","Pclass":"3","Name":"Palsson, Miss. Torborg Danira","Sex":"female","Age":"8","SibSp":"3","Parch":"1","Ticket":"349909","Fare":"21.075","Cabin":"","Embarked":"S"},
    {"PassengerId":"26","Survived":"1","Pclass":"3","Name":"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)","Sex":"female","Age":"38","SibSp":"1","Parch":"5","Ticket":"347077","Fare":"31.3875","Cabin":"","Embarked":"S"},
    {"PassengerId":"27","Survived":"0","Pclass":"3","Name":"Emir, Mr. Farred Chehab","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"2631","Fare":"7.225","Cabin":"","Embarked":"C"},
    {"PassengerId":"28","Survived":"0","Pclass":"1","Name":"Fortune, Mr. Charles Alexander","Sex":"male","Age":"19","SibSp":"3","Parch":"2","Ticket":"19950","Fare":"263","Cabin":"C23 C25 C27","Embarked":"S"},
    {"PassengerId":"30","Survived":"0","Pclass":"3","Name":"Todoroff, Mr. Lalio","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"349216","Fare":"7.8958","Cabin":"","Embarked":"S"},
    {"PassengerId":"31","Survived":"0","Pclass":"1","Name":"Uruchurtu, Don. Manuel E","Sex":"male","Age":"40","SibSp":"0","Parch":"0","Ticket":"PC 17601","Fare":"27.7208","Cabin":"","Embarked":"C"},
    {"PassengerId":"32","Survived":"1","Pclass":"1","Name":"Spencer, Mrs. William Augustus (Marie Eugenie)","Sex":"female","Age":"","SibSp":"1","Parch":"0","Ticket":"PC 17569","Fare":"146.5208","Cabin":"B78","Embarked":"C"},
    {"PassengerId":"33","Survived":"1","Pclass":"3","Name":"Glynn, Miss. Mary Agatha","Sex":"female","Age":"","SibSp":"0","Parch":"0","Ticket":"335677","Fare":"7.75","Cabin":"","Embarked":"Q"},
    {"PassengerId":"34","Survived":"0","Pclass":"2","Name":"Wheadon, Mr. Edward H","Sex":"male","Age":"66","SibSp":"0","Parch":"0","Ticket":"C.A. 24579","Fare":"10.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"35","Survived":"0","Pclass":"1","Name":"Meyer, Mr. Edgar Joseph","Sex":"male","Age":"28","SibSp":"1","Parch":"0","Ticket":"PC 17604","Fare":"82.1708","Cabin":"","Embarked":"C"},
    {"PassengerId":"36","Survived":"0","Pclass":"1","Name":"Holverson, Mr. Alexander Oskar","Sex":"male","Age":"42","SibSp":"1","Parch":"0","Ticket":"113789","Fare":"52","Cabin":"","Embarked":"S"},
    {"PassengerId":"37","Survived":"1","Pclass":"3","Name":"Mamee, Mr. Hanna","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"2677","Fare":"7.2292","Cabin":"","Embarked":"C"},
    {"PassengerId":"38","Survived":"0","Pclass":"3","Name":"Cann, Mr. Ernest Charles","Sex":"male","Age":"21","SibSp":"0","Parch":"0","Ticket":"A./5. 2152","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"39","Survived":"0","Pclass":"3","Name":"Vander Planke, Miss. Augusta Maria","Sex":"female","Age":"18","SibSp":"2","Parch":"0","Ticket":"345764","Fare":"18","Cabin":"","Embarked":"S"},
    {"PassengerId":"40","Survived":"1","Pclass":"3","Name":"Nicola-Yarred, Miss. Jamila","Sex":"female","Age":"14","SibSp":"1","Parch":"0","Ticket":"2651","Fare":"11.2417","Cabin":"","Embarked":"C"},
    {"PassengerId":"41","Survived":"0","Pclass":"3","Name":"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)","Sex":"female","Age":"40","SibSp":"1","Parch":"0","Ticket":"7546","Fare":"9.475","Cabin":"","Embarked":"S"},
    {"PassengerId":"42","Survived":"0","Pclass":"2","Name":"Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)","Sex":"female","Age":"27","SibSp":"1","Parch":"0","Ticket":"11668","Fare":"21","Cabin":"","Embarked":"S"},
    {"PassengerId":"43","Survived":"0","Pclass":"3","Name":"Kraeff, Mr. Theodor","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"349253","Fare":"7.8958","Cabin":"","Embarked":"C"},
    {"PassengerId":"44","Survived":"1","Pclass":"2","Name":"Laroche, Miss. Simonne Marie Anne Andree","Sex":"female","Age":"3","SibSp":"1","Parch":"2","Ticket":"SC/Paris 2123","Fare":"41.5792","Cabin":"","Embarked":"C"},
    {"PassengerId":"45","Survived":"1","Pclass":"3","Name":"Devaney, Miss. Margaret Delia","Sex":"female","Age":"19","SibSp":"0","Parch":"0","Ticket":"330958","Fare":"7.8792","Cabin":"","Embarked":"Q"},
    {"PassengerId":"46","Survived":"0","Pclass":"3","Name":"Rogers, Mr. William John","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"S.C./A.4. 23567","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"47","Survived":"0","Pclass":"3","Name":"Lennon, Mr. Denis","Sex":"male","Age":"","SibSp":"1","Parch":"0","Ticket":"370371","Fare":"15.5","Cabin":"","Embarked":"Q"},
    {"PassengerId":"48","Survived":"1","Pclass":"3","Name":"O'Driscoll, Miss. Bridget","Sex":"female","Age":"","SibSp":"0","Parch":"0","Ticket":"14311","Fare":"7.75","Cabin":"","Embarked":"Q"},
    {"PassengerId":"49","Survived":"0","Pclass":"3","Name":"Samaan, Mr. Youssef","Sex":"male","Age":"","SibSp":"2","Parch":"0","Ticket":"2662","Fare":"21.6792","Cabin":"","Embarked":"C"},
    {"PassengerId":"50","Survived":"0","Pclass":"3","Name":"Arnold-Franchi, Mrs. Josef (Josefine Franchi)","Sex":"female","Age":"18","SibSp":"1","Parch":"0","Ticket":"349237","Fare":"17.8","Cabin":"","Embarked":"S"},
    {"PassengerId":"51","Survived":"0","Pclass":"3","Name":"Panula, Master. Juha Niilo","Sex":"male","Age":"7","SibSp":"4","Parch":"1","Ticket":"3101295","Fare":"39.6875","Cabin":"","Embarked":"S"},
    {"PassengerId":"52","Survived":"0","Pclass":"3","Name":"Nosworthy, Mr. Richard Cater","Sex":"male","Age":"21","SibSp":"0","Parch":"0","Ticket":"A/4. 39886","Fare":"7.8","Cabin":"","Embarked":"S"},
    {"PassengerId":"53","Survived":"1","Pclass":"1","Name":"Harper, Mrs. Henry Sleeper (Myna Haxtun)","Sex":"female","Age":"49","SibSp":"1","Parch":"0","Ticket":"PC 17572","Fare":"76.7292","Cabin":"D33","Embarked":"C"},
    {"PassengerId":"54","Survived":"1","Pclass":"2","Name":"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)","Sex":"female","Age":"29","SibSp":"1","Parch":"0","Ticket":"2926","Fare":"26","Cabin":"","Embarked":"S"},
    {"PassengerId":"55","Survived":"0","Pclass":"1","Name":"Ostby, Mr. Engelhart Cornelius","Sex":"male","Age":"65","SibSp":"0","Parch":"1","Ticket":"113509","Fare":"61.9792","Cabin":"B30","Embarked":"C"},
    {"PassengerId":"56","Survived":"1","Pclass":"1","Name":"Woolner, Mr. Hugh","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"19947","Fare":"35.5","Cabin":"C52","Embarked":"S"},
    {"PassengerId":"57","Survived":"1","Pclass":"2","Name":"Rugg, Miss. Emily","Sex":"female","Age":"21","SibSp":"0","Parch":"0","Ticket":"C.A. 31026","Fare":"10.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"58","Survived":"0","Pclass":"3","Name":"Novel, Mr. Mansouer","Sex":"male","Age":"28.5","SibSp":"0","Parch":"0","Ticket":"2697","Fare":"7.2292","Cabin":"","Embarked":"C"},
    {"PassengerId":"59","Survived":"1","Pclass":"2","Name":"West, Miss. Constance Mirium","Sex":"female","Age":"5","SibSp":"1","Parch":"2","Ticket":"C.A. 34651","Fare":"27.75","Cabin":"","Embarked":"S"},
    {"PassengerId":"60","Survived":"0","Pclass":"3","Name":"Goodwin, Master. William Frederick","Sex":"male","Age":"11","SibSp":"5","Parch":"2","Ticket":"CA 2144","Fare":"46.9","Cabin":"","Embarked":"S"},
    {"PassengerId":"61","Survived":"0","Pclass":"3","Name":"Sirayanian, Mr. Orsen","Sex":"male","Age":"22","SibSp":"0","Parch":"0","Ticket":"2669","Fare":"7.2292","Cabin":"","Embarked":"C"},
    {"PassengerId":"62","Survived":"1","Pclass":"1","Name":"Icard, Miss. Amelie","Sex":"female","Age":"38","SibSp":"0","Parch":"0","Ticket":"113572","Fare":"80","Cabin":"B28","Embarked":""},
    {"PassengerId":"63","Survived":"0","Pclass":"1","Name":"Harris, Mr. Henry Birkhardt","Sex":"male","Age":"45","SibSp":"1","Parch":"0","Ticket":"36973","Fare":"83.475","Cabin":"C83","Embarked":"S"},
    {"PassengerId":"64","Survived":"0","Pclass":"3","Name":"Skoog, Master. Harald","Sex":"male","Age":"4","SibSp":"3","Parch":"2","Ticket":"347088","Fare":"27.9","Cabin":"","Embarked":"S"},
    {"PassengerId":"65","Survived":"0","Pclass":"1","Name":"Stewart, Mr. Albert A","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"PC 17605","Fare":"27.7208","Cabin":"","Embarked":"C"},
    {"PassengerId":"66","Survived":"1","Pclass":"3","Name":"Moubarek, Master. Gerios","Sex":"male","Age":"","SibSp":"1","Parch":"1","Ticket":"2661","Fare":"15.2458","Cabin":"","Embarked":"C"},
    {"PassengerId":"67","Survived":"1","Pclass":"2","Name":"Nye, Mrs. (Elizabeth Ramell)","Sex":"female","Age":"29","SibSp":"0","Parch":"0","Ticket":"C.A. 29395","Fare":"10.5","Cabin":"F33","Embarked":"S"},
    {"PassengerId":"68","Survived":"0","Pclass":"3","Name":"Crease, Mr. Ernest James","Sex":"male","Age":"19","SibSp":"0","Parch":"0","Ticket":"S.P. 3464","Fare":"8.1583","Cabin":"","Embarked":"S"},
    {"PassengerId":"69","Survived":"1","Pclass":"3","Name":"Andersson, Miss. Erna Alexandra","Sex":"female","Age":"17","SibSp":"4","Parch":"2","Ticket":"3101281","Fare":"7.925","Cabin":"","Embarked":"S"},
    {"PassengerId":"70","Survived":"0","Pclass":"3","Name":"Kink, Mr. Vincenz","Sex":"male","Age":"26","SibSp":"2","Parch":"0","Ticket":"315151","Fare":"8.6625","Cabin":"","Embarked":"S"},
    {"PassengerId":"71","Survived":"0","Pclass":"2","Name":"Jenkin, Mr. Stephen Curnow","Sex":"male","Age":"32","SibSp":"0","Parch":"0","Ticket":"C.A. 33111","Fare":"10.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"72","Survived":"0","Pclass":"3","Name":"Goodwin, Miss. Lillian Amy","Sex":"female","Age":"16","SibSp":"5","Parch":"2","Ticket":"CA 2144","Fare":"46.9","Cabin":"","Embarked":"S"},
    {"PassengerId":"73","Survived":"0","Pclass":"2","Name":"Hood, Mr. Ambrose Jr","Sex":"male","Age":"21","SibSp":"0","Parch":"0","Ticket":"S.O.C. 14879","Fare":"73.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"74","Survived":"0","Pclass":"3","Name":"Chronopoulos, Mr. Apostolos","Sex":"male","Age":"26","SibSp":"1","Parch":"0","Ticket":"2680","Fare":"14.4542","Cabin":"","Embarked":"C"},
    {"PassengerId":"75","Survived":"1","Pclass":"3","Name":"Bing, Mr. Lee","Sex":"male","Age":"32","SibSp":"0","Parch":"0","Ticket":"1601","Fare":"56.4958","Cabin":"","Embarked":"S"},
    {"PassengerId":"76","Survived":"0","Pclass":"3","Name":"Moen, Mr. Sigurd Hansen","Sex":"male","Age":"25","SibSp":"0","Parch":"0","Ticket":"348123","Fare":"7.65","Cabin":"F G73","Embarked":"S"},
    {"PassengerId":"77","Survived":"0","Pclass":"3","Name":"Staneff, Mr. Ivan","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"349208","Fare":"7.8958","Cabin":"","Embarked":"S"},
    {"PassengerId":"78","Survived":"0","Pclass":"3","Name":"Moutal, Mr. Rahamin Haim","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"374746","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"79","Survived":"1","Pclass":"2","Name":"Caldwell, Master. Alden Gates","Sex":"male","Age":"0.83","SibSp":"0","Parch":"2","Ticket":"248738","Fare":"29","Cabin":"","Embarked":"S"},
    {"PassengerId":"80","Survived":"1","Pclass":"3","Name":"Dowdell, Miss. Elizabeth","Sex":"female","Age":"30","SibSp":"0","Parch":"0","Ticket":"364516","Fare":"12.475","Cabin":"","Embarked":"S"},
    {"PassengerId":"81","Survived":"0","Pclass":"3","Name":"Waelens, Mr. Achille","Sex":"male","Age":"22","SibSp":"0","Parch":"0","Ticket":"345767","Fare":"9","Cabin":"","Embarked":"S"},
    {"PassengerId":"82","Survived":"1","Pclass":"3","Name":"Sheerlinck, Mr. Jan Baptist","Sex":"male","Age":"29","SibSp":"0","Parch":"0","Ticket":"345779","Fare":"9.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"83","Survived":"1","Pclass":"3","Name":"McDermott, Miss. Brigdet Delia","Sex":"female","Age":"","SibSp":"0","Parch":"0","Ticket":"330932","Fare":"7.7875","Cabin":"","Embarked":"Q"},
    {"PassengerId":"84","Survived":"0","Pclass":"1","Name":"Carrau, Mr. Francisco M","Sex":"male","Age":"28","SibSp":"0","Parch":"0","Ticket":"113059","Fare":"47.1","Cabin":"","Embarked":"S"},
    {"PassengerId":"85","Survived":"1","Pclass":"2","Name":"Ilett, Miss. Bertha","Sex":"female","Age":"17","SibSp":"0","Parch":"0","Ticket":"SO/C 14885","Fare":"10.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"86","Survived":"1","Pclass":"3","Name":"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)","Sex":"female","Age":"33","SibSp":"3","Parch":"0","Ticket":"3101278","Fare":"15.85","Cabin":"","Embarked":"S"},
    {"PassengerId":"87","Survived":"0","Pclass":"3","Name":"Ford, Mr. William Neal","Sex":"male","Age":"16","SibSp":"1","Parch":"3","Ticket":"W./C. 6608","Fare":"34.375","Cabin":"","Embarked":"S"},
    {"PassengerId":"88","Survived":"0","Pclass":"3","Name":"Slocovski, Mr. Selman Francis","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"SOTON/OQ 392086","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"89","Survived":"1","Pclass":"1","Name":"Fortune, Miss. Mabel Helen","Sex":"female","Age":"23","SibSp":"3","Parch":"2","Ticket":"19950","Fare":"263","Cabin":"C23 C25 C27","Embarked":"S"},
    {"PassengerId":"90","Survived":"0","Pclass":"3","Name":"Celotti, Mr. Francesco","Sex":"male","Age":"24","SibSp":"0","Parch":"0","Ticket":"343275","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"91","Survived":"0","Pclass":"3","Name":"Christmann, Mr. Emil","Sex":"male","Age":"29","SibSp":"0","Parch":"0","Ticket":"343276","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"92","Survived":"0","Pclass":"3","Name":"Andreasson, Mr. Paul Edvin","Sex":"male","Age":"20","SibSp":"0","Parch":"0","Ticket":"347466","Fare":"7.8542","Cabin":"","Embarked":"S"},
    {"PassengerId":"93","Survived":"0","Pclass":"1","Name":"Chaffee, Mr. Herbert Fuller","Sex":"male","Age":"46","SibSp":"1","Parch":"0","Ticket":"W.E.P. 5734","Fare":"61.175","Cabin":"E31","Embarked":"S"},
    {"PassengerId":"94","Survived":"0","Pclass":"3","Name":"Dean, Mr. Bertram Frank","Sex":"male","Age":"26","SibSp":"1","Parch":"2","Ticket":"C.A. 2315","Fare":"20.575","Cabin":"","Embarked":"S"},
    {"PassengerId":"95","Survived":"0","Pclass":"3","Name":"Coxon, Mr. Daniel","Sex":"male","Age":"59","SibSp":"0","Parch":"0","Ticket":"364500","Fare":"7.25","Cabin":"","Embarked":"S"},
    {"PassengerId":"96","Survived":"0","Pclass":"3","Name":"Shorney, Mr. Charles Joseph","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"374910","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"97","Survived":"0","Pclass":"1","Name":"Goldschmidt, Mr. George B","Sex":"male","Age":"71","SibSp":"0","Parch":"0","Ticket":"PC 17754","Fare":"34.6542","Cabin":"A5","Embarked":"C"},
    {"PassengerId":"98","Survived":"1","Pclass":"1","Name":"Greenfield, Mr. William Bertram","Sex":"male","Age":"23","SibSp":"0","Parch":"1","Ticket":"PC 17759","Fare":"63.3583","Cabin":"D10 D12","Embarked":"C"},
    {"PassengerId":"99","Survived":"1","Pclass":"2","Name":"Doling, Mrs. John T (Ada Julia Bone)","Sex":"female","Age":"34","SibSp":"0","Parch":"1","Ticket":"231919","Fare":"23","Cabin":"","Embarked":"S"},
    {"PassengerId":"100","Survived":"0","Pclass":"2","Name":"Kantor, Mr. Sinai","Sex":"male","Age":"34","SibSp":"1","Parch":"0","Ticket":"244367","Fare":"26","Cabin":"","Embarked":"S"},
    {"PassengerId":"101","Survived":"0","Pclass":"3","Name":"Petranec, Miss. Matilda","Sex":"female","Age":"28","SibSp":"0","Parch":"0","Ticket":"349245","Fare":"7.8958","Cabin":"","Embarked":"S"},
    {"PassengerId":"103","Survived":"0","Pclass":"1","Name":"White, Mr. Richard Frasar","Sex":"male","Age":"21","SibSp":"0","Parch":"1","Ticket":"35281","Fare":"77.2875","Cabin":"D26","Embarked":"S"},
    {"PassengerId":"104","Survived":"0","Pclass":"3","Name":"Johansson, Mr. Gustaf Joel","Sex":"male","Age":"33","SibSp":"0","Parch":"0","Ticket":"7540","Fare":"8.6542","Cabin":"","Embarked":"S"},
    {"PassengerId":"105","Survived":"0","Pclass":"3","Name":"Gustafsson, Mr. Anders Vilhelm","Sex":"male","Age":"37","SibSp":"2","Parch":"0","Ticket":"3101276","Fare":"7.925","Cabin":"","Embarked":"S"},
    {"PassengerId":"106","Survived":"0","Pclass":"3","Name":"Mionoff, Mr. Stoytcho","Sex":"male","Age":"28","SibSp":"0","Parch":"0","Ticket":"349207","Fare":"7.8958","Cabin":"","Embarked":"S"},
    {"PassengerId":"107","Survived":"1","Pclass":"3","Name":"Salkjelsvik, Miss. Anna Kristine","Sex":"female","Age":"21","SibSp":"0","Parch":"0","Ticket":"343120","Fare":"7.65","Cabin":"","Embarked":"S"},
    {"PassengerId":"108","Survived":"1","Pclass":"3","Name":"Moss, Mr. Albert Johan","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"312991","Fare":"7.775","Cabin":"","Embarked":"S"},
    {"PassengerId":"109","Survived":"0","Pclass":"3","Name":"Rekic, Mr. Tido","Sex":"male","Age":"38","SibSp":"0","Parch":"0","Ticket":"349249","Fare":"7.8958","Cabin":"","Embarked":"S"},
    {"PassengerId":"110","Survived":"1","Pclass":"3","Name":"Moran, Miss. Bertha","Sex":"female","Age":"","SibSp":"1","Parch":"0","Ticket":"371110","Fare":"24.15","Cabin":"","Embarked":"Q"},
    {"PassengerId":"111","Survived":"0","Pclass":"1","Name":"Porter, Mr. Walter Chamberlain","Sex":"male","Age":"47","SibSp":"0","Parch":"0","Ticket":"110465","Fare":"52","Cabin":"C110","Embarked":"S"},
    {"PassengerId":"112","Survived":"0","Pclass":"3","Name":"Zabour, Miss. Hileni","Sex":"female","Age":"14.5","SibSp":"1","Parch":"0","Ticket":"2665","Fare":"14.4542","Cabin":"","Embarked":"C"},
    {"PassengerId":"113","Survived":"0","Pclass":"3","Name":"Barton, Mr. David John","Sex":"male","Age":"22","SibSp":"0","Parch":"0","Ticket":"324669","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"114","Survived":"0","Pclass":"3","Name":"Jussila, Miss. Katriina","Sex":"female","Age":"20","SibSp":"1","Parch":"0","Ticket":"4136","Fare":"9.825","Cabin":"","Embarked":"S"},
    {"PassengerId":"115","Survived":"0","Pclass":"3","Name":"Attalah, Miss. Malake","Sex":"female","Age":"17","SibSp":"0","Parch":"0","Ticket":"2627","Fare":"14.4583","Cabin":"","Embarked":"C"},
    {"PassengerId":"116","Survived":"0","Pclass":"3","Name":"Pekoniemi, Mr. Edvard","Sex":"male","Age":"21","SibSp":"0","Parch":"0","Ticket":"STON/O 2. 3101294","Fare":"7.925","Cabin":"","Embarked":"S"},
    {"PassengerId":"117","Survived":"0","Pclass":"3","Name":"Connors, Mr. Patrick","Sex":"male","Age":"70.5","SibSp":"0","Parch":"0","Ticket":"370369","Fare":"7.75","Cabin":"","Embarked":"Q"},
    {"PassengerId":"118","Survived":"0","Pclass":"2","Name":"Turpin, Mr. William John Robert","Sex":"male","Age":"29","SibSp":"1","Parch":"0","Ticket":"11668","Fare":"21","Cabin":"","Embarked":"S"},
    {"PassengerId":"119","Survived":"0","Pclass":"1","Name":"Baxter, Mr. Quigg Edmond","Sex":"male","Age":"24","SibSp":"0","Parch":"1","Ticket":"PC 17558","Fare":"247.5208","Cabin":"B58 B60","Embarked":"C"},
    {"PassengerId":"120","Survived":"0","Pclass":"3","Name":"Andersson, Miss. Ellis Anna Maria","Sex":"female","Age":"2","SibSp":"4","Parch":"2","Ticket":"347082","Fare":"31.275","Cabin":"","Embarked":"S"},
    {"PassengerId":"121","Survived":"0","Pclass":"2","Name":"Hickman, Mr. Stanley George","Sex":"male","Age":"21","SibSp":"2","Parch":"0","Ticket":"S.O.C. 14879","Fare":"73.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"122","Survived":"0","Pclass":"3","Name":"Moore, Mr. Leonard Charles","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"A4. 54510","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"123","Survived":"0","Pclass":"2","Name":"Nasser, Mr. Nicholas","Sex":"male","Age":"32.5","SibSp":"1","Parch":"0","Ticket":"237736","Fare":"30.0708","Cabin":"","Embarked":"C"},
    {"PassengerId":"124","Survived":"1","Pclass":"2","Name":"Webber, Miss. Susan","Sex":"female","Age":"32.5","SibSp":"0","Parch":"0","Ticket":"27267","Fare":"13","Cabin":"E101","Embarked":"S"},
    {"PassengerId":"125","Survived":"0","Pclass":"1","Name":"White, Mr. Percival Wayland","Sex":"male","Age":"54","SibSp":"0","Parch":"1","Ticket":"35281","Fare":"77.2875","Cabin":"D26","Embarked":"S"},
    {"PassengerId":"126","Survived":"1","Pclass":"3","Name":"Nicola-Yarred, Master. Elias","Sex":"male","Age":"12","SibSp":"1","Parch":"0","Ticket":"2651","Fare":"11.2417","Cabin":"","Embarked":"C"},
    {"PassengerId":"127","Survived":"0","Pclass":"3","Name":"McMahon, Mr. Martin","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"370372","Fare":"7.75","Cabin":"","Embarked":"Q"},
    {"PassengerId":"128","Survived":"1","Pclass":"3","Name":"Madsen, Mr. Fridtjof Arne","Sex":"male","Age":"24","SibSp":"0","Parch":"0","Ticket":"C 17369","Fare":"7.1417","Cabin":"","Embarked":"S"},
    {"PassengerId":"129","Survived":"1","Pclass":"3","Name":"Peter, Miss. Anna","Sex":"female","Age":"","SibSp":"1","Parch":"1","Ticket":"2668","Fare":"22.3583","Cabin":"F E69","Embarked":"C"},
    {"PassengerId":"130","Survived":"0","Pclass":"3","Name":"Ekstrom, Mr. Johan","Sex":"male","Age":"45","SibSp":"0","Parch":"0","Ticket":"347061","Fare":"6.975","Cabin":"","Embarked":"S"},
    {"PassengerId":"131","Survived":"0","Pclass":"3","Name":"Drazenoic, Mr. Jozef","Sex":"male","Age":"33","SibSp":"0","Parch":"0","Ticket":"349241","Fare":"7.8958","Cabin":"","Embarked":"C"},
    {"PassengerId":"132","Survived":"0","Pclass":"3","Name":"Coelho, Mr. Domingos Fernandeo","Sex":"male","Age":"20","SibSp":"0","Parch":"0","Ticket":"SOTON/O.Q. 3101307","Fare":"7.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"133","Survived":"0","Pclass":"3","Name":"Robins, Mrs. Alexander A (Grace Charity Laury)","Sex":"female","Age":"47","SibSp":"1","Parch":"0","Ticket":"A/5. 3337","Fare":"14.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"134","Survived":"1","Pclass":"2","Name":"Weisz, Mrs. Leopold (Mathilde Francoise Pede)","Sex":"female","Age":"29","SibSp":"1","Parch":"0","Ticket":"228414","Fare":"26","Cabin":"","Embarked":"S"},
    {"PassengerId":"135","Survived":"0","Pclass":"2","Name":"Sobey, Mr. Samuel James Hayden","Sex":"male","Age":"25","SibSp":"0","Parch":"0","Ticket":"C.A. 29178","Fare":"13","Cabin":"","Embarked":"S"},
    {"PassengerId":"136","Survived":"0","Pclass":"2","Name":"Richard, Mr. Emile","Sex":"male","Age":"23","SibSp":"0","Parch":"0","Ticket":"SC/PARIS 2133","Fare":"15.0458","Cabin":"","Embarked":"C"},
    {"PassengerId":"137","Survived":"1","Pclass":"1","Name":"Newsom, Miss. Helen Monypeny","Sex":"female","Age":"19","SibSp":"0","Parch":"2","Ticket":"11752","Fare":"26.2833","Cabin":"D47","Embarked":"S"},
    {"PassengerId":"138","Survived":"0","Pclass":"1","Name":"Futrelle, Mr. Jacques Heath","Sex":"male","Age":"37","SibSp":"1","Parch":"0","Ticket":"113803","Fare":"53.1","Cabin":"C123","Embarked":"S"},
    {"PassengerId":"139","Survived":"0","Pclass":"3","Name":"Osen, Mr. Olaf Elon","Sex":"male","Age":"16","SibSp":"0","Parch":"0","Ticket":"7534","Fare":"9.2167","Cabin":"","Embarked":"S"},
    {"PassengerId":"140","Survived":"0","Pclass":"1","Name":"Giglio, Mr. Victor","Sex":"male","Age":"24","SibSp":"0","Parch":"0","Ticket":"PC 17593","Fare":"79.2","Cabin":"B86","Embarked":"C"},
    {"PassengerId":"141","Survived":"0","Pclass":"3","Name":"Boulos, Mrs. Joseph (Sultana)","Sex":"female","Age":"","SibSp":"0","Parch":"2","Ticket":"2678","Fare":"15.2458","Cabin":"","Embarked":"C"},
    {"PassengerId":"142","Survived":"1","Pclass":"3","Name":"Nysten, Miss. Anna Sofia","Sex":"female","Age":"22","SibSp":"0","Parch":"0","Ticket":"347081","Fare":"7.75","Cabin":"","Embarked":"S"},
    {"PassengerId":"143","Survived":"1","Pclass":"3","Name":"Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)","Sex":"female","Age":"24","SibSp":"1","Parch":"0","Ticket":"STON/O2. 3101279","Fare":"15.85","Cabin":"","Embarked":"S"},
    {"PassengerId":"144","Survived":"0","Pclass":"3","Name":"Burke, Mr. Jeremiah","Sex":"male","Age":"19","SibSp":"0","Parch":"0","Ticket":"365222","Fare":"6.75","Cabin":"","Embarked":"Q"},
    {"PassengerId":"145","Survived":"0","Pclass":"2","Name":"Andrew, Mr. Edgardo Samuel","Sex":"male","Age":"18","SibSp":"0","Parch":"0","Ticket":"231945","Fare":"11.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"146","Survived":"0","Pclass":"2","Name":"Nicholls, Mr. Joseph Charles","Sex":"male","Age":"19","SibSp":"1","Parch":"1","Ticket":"C.A. 33112","Fare":"36.75","Cabin":"","Embarked":"S"},
    {"PassengerId":"151","Survived":"0","Pclass":"2","Name":"Bateman, Rev. Robert James","Sex":"male","Age":"51","SibSp":"0","Parch":"0","Ticket":"S.O.P. 1166","Fare":"12.525","Cabin":"","Embarked":"S"},
    {"PassengerId":"152","Survived":"1","Pclass":"1","Name":"Pears, Mrs. Thomas (Edith Wearne)","Sex":"female","Age":"22","SibSp":"1","Parch":"0","Ticket":"113776","Fare":"66.6","Cabin":"C2","Embarked":"S"},
    {"PassengerId":"153","Survived":"0","Pclass":"3","Name":"Meo, Mr. Alfonzo","Sex":"male","Age":"55.5","SibSp":"0","Parch":"0","Ticket":"A.5. 11206","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"154","Survived":"0","Pclass":"3","Name":"van Billiard, Mr. Austin Blyler","Sex":"male","Age":"40.5","SibSp":"0","Parch":"2","Ticket":"A/5. 851","Fare":"14.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"155","Survived":"0","Pclass":"3","Name":"Olsen, Mr. Ole Martin","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"Fa 265302","Fare":"7.3125","Cabin":"","Embarked":"S"},
    {"PassengerId":"156","Survived":"0","Pclass":"1","Name":"Williams, Mr. Charles Duane","Sex":"male","Age":"51","SibSp":"0","Parch":"1","Ticket":"PC 17597","Fare":"61.3792","Cabin":"","Embarked":"C"},
    {"PassengerId":"158","Survived":"0","Pclass":"3","Name":"Corn, Mr. Harry","Sex":"male","Age":"30","SibSp":"0","Parch":"0","Ticket":"SOTON/OQ 392090","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"159","Survived":"0","Pclass":"3","Name":"Smiljanic, Mr. Mile","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"315037","Fare":"8.6625","Cabin":"","Embarked":"S"},
    {"PassengerId":"160","Survived":"0","Pclass":"3","Name":"Sage, Master. Thomas Henry","Sex":"male","Age":"","SibSp":"8","Parch":"2","Ticket":"CA. 2343","Fare":"69.55","Cabin":"","Embarked":"S"},
     {"PassengerId":"891","Survived":"0","Pclass":"3","Name":"Dooley, Mr. Patrick","Sex":"male","Age":"32","SibSp":"0","Parch":"0","Ticket":"370376","Fare":"7.75","Cabin":"","Embarked":"Q"}
    ];