export const data = [
    {"PassengerId":"892","Pclass":"3","Name":"Kelly, Mr. James","Sex":"male","Age":"34.5","SibSp":"0","Parch":"0","Ticket":"330911","Fare":"7.8292","Cabin":"","Embarked":"Q"},
    {"PassengerId":"893","Pclass":"3","Name":"Wilkes, Mrs. James (Ellen Needs)","Sex":"female","Age":"47","SibSp":"1","Parch":"0","Ticket":"363272","Fare":"7","Cabin":"","Embarked":"S"},
    {"PassengerId":"894","Pclass":"2","Name":"Myles, Mr. Thomas Francis","Sex":"male","Age":"62","SibSp":"0","Parch":"0","Ticket":"240276","Fare":"9.6875","Cabin":"","Embarked":"Q"},
    {"PassengerId":"895","Pclass":"3","Name":"Wirz, Mr. Albert","Sex":"male","Age":"27","SibSp":"0","Parch":"0","Ticket":"315154","Fare":"8.6625","Cabin":"","Embarked":"S"},
    {"PassengerId":"896","Pclass":"3","Name":"Hirvonen, Mrs. Alexander (Helga E Lindqvist)","Sex":"female","Age":"22","SibSp":"1","Parch":"1","Ticket":"3101298","Fare":"12.2875","Cabin":"","Embarked":"S"},
    {"PassengerId":"897","Pclass":"3","Name":"Svensson, Mr. Johan Cervin","Sex":"male","Age":"14","SibSp":"0","Parch":"0","Ticket":"7538","Fare":"9.225","Cabin":"","Embarked":"S"},
    {"PassengerId":"898","Pclass":"3","Name":"Connolly, Miss. Kate","Sex":"female","Age":"30","SibSp":"0","Parch":"0","Ticket":"330972","Fare":"7.6292","Cabin":"","Embarked":"Q"},
    {"PassengerId":"899","Pclass":"2","Name":"Caldwell, Mr. Albert Francis","Sex":"male","Age":"26","SibSp":"1","Parch":"1","Ticket":"248738","Fare":"29","Cabin":"","Embarked":"S"},
    {"PassengerId":"900","Pclass":"3","Name":"Abrahim, Mrs. Joseph (Sophie Halaut Easu)","Sex":"female","Age":"18","SibSp":"0","Parch":"0","Ticket":"2657","Fare":"7.2292","Cabin":"","Embarked":"C"},
    {"PassengerId":"901","Pclass":"3","Name":"Davies, Mr. John Samuel","Sex":"male","Age":"21","SibSp":"2","Parch":"0","Ticket":"A/4 48871","Fare":"24.15","Cabin":"","Embarked":"S"},
    {"PassengerId":"902","Pclass":"3","Name":"Ilieff, Mr. Ylio","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"349220","Fare":"7.8958","Cabin":"","Embarked":"S"},
    {"PassengerId":"903","Pclass":"1","Name":"Jones, Mr. Charles Cresson","Sex":"male","Age":"46","SibSp":"0","Parch":"0","Ticket":"694","Fare":"26","Cabin":"","Embarked":"S"},
    {"PassengerId":"904","Pclass":"1","Name":"Snyder, Mrs. John Pillsbury (Nelle Stevenson)","Sex":"female","Age":"23","SibSp":"1","Parch":"0","Ticket":"21228","Fare":"82.2667","Cabin":"B45","Embarked":"S"},
    {"PassengerId":"905","Pclass":"2","Name":"Howard, Mr. Benjamin","Sex":"male","Age":"63","SibSp":"1","Parch":"0","Ticket":"24065","Fare":"26","Cabin":"","Embarked":"S"},
    {"PassengerId":"906","Pclass":"1","Name":"Chaffee, Mrs. Herbert Fuller (Carrie Constance Toogood)","Sex":"female","Age":"47","SibSp":"1","Parch":"0","Ticket":"W.E.P. 5734","Fare":"61.175","Cabin":"E31","Embarked":"S"},
    {"PassengerId":"907","Pclass":"2","Name":"del Carlo, Mrs. Sebastiano (Argenia Genovesi)","Sex":"female","Age":"24","SibSp":"1","Parch":"0","Ticket":"SC/PARIS 2167","Fare":"27.7208","Cabin":"","Embarked":"C"},
    {"PassengerId":"908","Pclass":"2","Name":"Keane, Mr. Daniel","Sex":"male","Age":"35","SibSp":"0","Parch":"0","Ticket":"233734","Fare":"12.35","Cabin":"","Embarked":"Q"},
    {"PassengerId":"909","Pclass":"3","Name":"Assaf, Mr. Gerios","Sex":"male","Age":"21","SibSp":"0","Parch":"0","Ticket":"2692","Fare":"7.225","Cabin":"","Embarked":"C"},
    {"PassengerId":"910","Pclass":"3","Name":"Ilmakangas, Miss. Ida Livija","Sex":"female","Age":"27","SibSp":"1","Parch":"0","Ticket":"STON/O2. 3101270","Fare":"7.925","Cabin":"","Embarked":"S"},
    {"PassengerId":"911","Pclass":"3","Name":"Assaf Khalil, Mrs. Mariana (Miriam)","Sex":"female","Age":"45","SibSp":"0","Parch":"0","Ticket":"2696","Fare":"7.225","Cabin":"","Embarked":"C"},
    {"PassengerId":"912","Pclass":"1","Name":"Rothschild, Mr. Martin","Sex":"male","Age":"55","SibSp":"1","Parch":"0","Ticket":"PC 17603","Fare":"59.4","Cabin":"","Embarked":"C"},
    {"PassengerId":"913","Pclass":"3","Name":"Olsen, Master. Artur Karl","Sex":"male","Age":"9","SibSp":"0","Parch":"1","Ticket":"C 17368","Fare":"3.1708","Cabin":"","Embarked":"S"},
    {"PassengerId":"914","Pclass":"1","Name":"Flegenheim, Mrs. Alfred (Antoinette)","Sex":"female","Age":"","SibSp":"0","Parch":"0","Ticket":"PC 17598","Fare":"31.6833","Cabin":"","Embarked":"S"},
    {"PassengerId":"915","Pclass":"1","Name":"Williams, Mr. Richard Norris II","Sex":"male","Age":"21","SibSp":"0","Parch":"1","Ticket":"PC 17597","Fare":"61.3792","Cabin":"","Embarked":"C"},
    {"PassengerId":"916","Pclass":"1","Name":"Ryerson, Mrs. Arthur Larned (Emily Maria Borie)","Sex":"female","Age":"48","SibSp":"1","Parch":"3","Ticket":"PC 17608","Fare":"262.375","Cabin":"B57 B59 B63 B66","Embarked":"C"},
    {"PassengerId":"917","Pclass":"3","Name":"Robins, Mr. Alexander A","Sex":"male","Age":"50","SibSp":"1","Parch":"0","Ticket":"A/5. 3337","Fare":"14.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"918","Pclass":"1","Name":"Ostby, Miss. Helene Ragnhild","Sex":"female","Age":"22","SibSp":"0","Parch":"1","Ticket":"113509","Fare":"61.9792","Cabin":"B36","Embarked":"C"},
    {"PassengerId":"919","Pclass":"3","Name":"Daher, Mr. Shedid","Sex":"male","Age":"22.5","SibSp":"0","Parch":"0","Ticket":"2698","Fare":"7.225","Cabin":"","Embarked":"C"},
    {"PassengerId":"920","Pclass":"1","Name":"Brady, Mr. John Bertram","Sex":"male","Age":"41","SibSp":"0","Parch":"0","Ticket":"113054","Fare":"30.5","Cabin":"A21","Embarked":"S"},
    {"PassengerId":"921","Pclass":"3","Name":"Samaan, Mr. Elias","Sex":"male","Age":"","SibSp":"2","Parch":"0","Ticket":"2662","Fare":"21.6792","Cabin":"","Embarked":"C"},
    {"PassengerId":"922","Pclass":"2","Name":"Louch, Mr. Charles Alexander","Sex":"male","Age":"50","SibSp":"1","Parch":"0","Ticket":"SC/AH 3085","Fare":"26","Cabin":"","Embarked":"S"},
    {"PassengerId":"923","Pclass":"2","Name":"Jefferys, Mr. Clifford Thomas","Sex":"male","Age":"24","SibSp":"2","Parch":"0","Ticket":"C.A. 31029","Fare":"31.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"924","Pclass":"3","Name":"Dean, Mrs. Bertram (Eva Georgetta Light)","Sex":"female","Age":"33","SibSp":"1","Parch":"2","Ticket":"C.A. 2315","Fare":"20.575","Cabin":"","Embarked":"S"},
    {"PassengerId":"925","Pclass":"3","Name":"Johnston, Mrs. Andrew G (Elizabeth Lily)","Sex":"female","Age":"","SibSp":"1","Parch":"2","Ticket":"W./C. 6607","Fare":"23.45","Cabin":"","Embarked":"S"},
    {"PassengerId":"926","Pclass":"1","Name":"Mock, Mr. Philipp Edmund","Sex":"male","Age":"30","SibSp":"1","Parch":"0","Ticket":"13236","Fare":"57.75","Cabin":"C78","Embarked":"C"},
    {"PassengerId":"927","Pclass":"3","Name":"Katavelas, Mr. Vassilios (Catavelas Vassilios","Sex":"male","Age":"18.5","SibSp":"0","Parch":"0","Ticket":"2682","Fare":"7.2292","Cabin":"","Embarked":"C"},
    {"PassengerId":"928","Pclass":"3","Name":"Roth, Miss. Sarah A","Sex":"female","Age":"","SibSp":"0","Parch":"0","Ticket":"342712","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"929","Pclass":"3","Name":"Cacic, Miss. Manda","Sex":"female","Age":"21","SibSp":"0","Parch":"0","Ticket":"315087","Fare":"8.6625","Cabin":"","Embarked":"S"},
    {"PassengerId":"930","Pclass":"3","Name":"Sap, Mr. Julius","Sex":"male","Age":"25","SibSp":"0","Parch":"0","Ticket":"345768","Fare":"9.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"931","Pclass":"3","Name":"Hee, Mr. Ling","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"1601","Fare":"56.4958","Cabin":"","Embarked":"S"},
    {"PassengerId":"932","Pclass":"3","Name":"Karun, Mr. Franz","Sex":"male","Age":"39","SibSp":"0","Parch":"1","Ticket":"349256","Fare":"13.4167","Cabin":"","Embarked":"C"},
    {"PassengerId":"933","Pclass":"1","Name":"Franklin, Mr. Thomas Parham","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"113778","Fare":"26.55","Cabin":"D34","Embarked":"S"},
    {"PassengerId":"934","Pclass":"3","Name":"Goldsmith, Mr. Nathan","Sex":"male","Age":"41","SibSp":"0","Parch":"0","Ticket":"SOTON/O.Q. 3101263","Fare":"7.85","Cabin":"","Embarked":"S"},
    {"PassengerId":"935","Pclass":"2","Name":"Corbett, Mrs. Walter H (Irene Colvin)","Sex":"female","Age":"30","SibSp":"0","Parch":"0","Ticket":"237249","Fare":"13","Cabin":"","Embarked":"S"},
    {"PassengerId":"936","Pclass":"1","Name":"Kimball, Mrs. Edwin Nelson Jr (Gertrude Parsons)","Sex":"female","Age":"45","SibSp":"1","Parch":"0","Ticket":"11753","Fare":"52.5542","Cabin":"D19","Embarked":"S"},
    {"PassengerId":"937","Pclass":"3","Name":"Peltomaki, Mr. Nikolai Johannes","Sex":"male","Age":"25","SibSp":"0","Parch":"0","Ticket":"STON/O 2. 3101291","Fare":"7.925","Cabin":"","Embarked":"S"},
    {"PassengerId":"938","Pclass":"1","Name":"Chevre, Mr. Paul Romaine","Sex":"male","Age":"45","SibSp":"0","Parch":"0","Ticket":"PC 17594","Fare":"29.7","Cabin":"A9","Embarked":"C"},
    {"PassengerId":"939","Pclass":"3","Name":"Shaughnessy, Mr. Patrick","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"370374","Fare":"7.75","Cabin":"","Embarked":"Q"},
    {"PassengerId":"940","Pclass":"1","Name":"Bucknell, Mrs. William Robert (Emma Eliza Ward)","Sex":"female","Age":"60","SibSp":"0","Parch":"0","Ticket":"11813","Fare":"76.2917","Cabin":"D15","Embarked":"C"},
    {"PassengerId":"941","Pclass":"3","Name":"Coutts, Mrs. William (Winnie Minnie)","Sex":"female","Age":"36","SibSp":"0","Parch":"2","Ticket":"C.A. 37671","Fare":"15.9","Cabin":"","Embarked":"S"},
    {"PassengerId":"942","Pclass":"1","Name":"Smith, Mr. Lucien Philip","Sex":"male","Age":"24","SibSp":"1","Parch":"0","Ticket":"13695","Fare":"60","Cabin":"C31","Embarked":"S"},
    {"PassengerId":"943","Pclass":"2","Name":"Pulbaum, Mr. Franz","Sex":"male","Age":"27","SibSp":"0","Parch":"0","Ticket":"SC/PARIS 2168","Fare":"15.0333","Cabin":"","Embarked":"C"},
    {"PassengerId":"944","Pclass":"2","Name":"Hocking, Miss. Ellen Nellie","Sex":"female","Age":"20","SibSp":"2","Parch":"1","Ticket":"29105","Fare":"23","Cabin":"","Embarked":"S"},
    {"PassengerId":"945","Pclass":"1","Name":"Fortune, Miss. Ethel Flora","Sex":"female","Age":"28","SibSp":"3","Parch":"2","Ticket":"19950","Fare":"263","Cabin":"C23 C25 C27","Embarked":"S"},
    {"PassengerId":"946","Pclass":"2","Name":"Mangiavacchi, Mr. Serafino Emilio","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"SC/A.3 2861","Fare":"15.5792","Cabin":"","Embarked":"C"},
    {"PassengerId":"947","Pclass":"3","Name":"Rice, Master. Albert","Sex":"male","Age":"10","SibSp":"4","Parch":"1","Ticket":"382652","Fare":"29.125","Cabin":"","Embarked":"Q"},
    {"PassengerId":"948","Pclass":"3","Name":"Cor, Mr. Bartol","Sex":"male","Age":"35","SibSp":"0","Parch":"0","Ticket":"349230","Fare":"7.8958","Cabin":"","Embarked":"S"},
    {"PassengerId":"949","Pclass":"3","Name":"Abelseth, Mr. Olaus Jorgensen","Sex":"male","Age":"25","SibSp":"0","Parch":"0","Ticket":"348122","Fare":"7.65","Cabin":"F G63","Embarked":"S"},
    {"PassengerId":"950","Pclass":"3","Name":"Davison, Mr. Thomas Henry","Sex":"male","Age":"","SibSp":"1","Parch":"0","Ticket":"386525","Fare":"16.1","Cabin":"","Embarked":"S"},
    {"PassengerId":"951","Pclass":"1","Name":"Chaudanson, Miss. Victorine","Sex":"female","Age":"36","SibSp":"0","Parch":"0","Ticket":"PC 17608","Fare":"262.375","Cabin":"B61","Embarked":"C"},
    {"PassengerId":"952","Pclass":"3","Name":"Dika, Mr. Mirko","Sex":"male","Age":"17","SibSp":"0","Parch":"0","Ticket":"349232","Fare":"7.8958","Cabin":"","Embarked":"S"},
    {"PassengerId":"953","Pclass":"2","Name":"McCrae, Mr. Arthur Gordon","Sex":"male","Age":"32","SibSp":"0","Parch":"0","Ticket":"237216","Fare":"13.5","Cabin":"","Embarked":"S"},
    {"PassengerId":"954","Pclass":"3","Name":"Bjorklund, Mr. Ernst Herbert","Sex":"male","Age":"18","SibSp":"0","Parch":"0","Ticket":"347090","Fare":"7.75","Cabin":"","Embarked":"S"},
    {"PassengerId":"955","Pclass":"3","Name":"Bradley, Miss. Bridget Delia","Sex":"female","Age":"22","SibSp":"0","Parch":"0","Ticket":"334914","Fare":"7.725","Cabin":"","Embarked":"Q"},
    {"PassengerId":"956","Pclass":"1","Name":"Ryerson, Master. John Borie","Sex":"male","Age":"13","SibSp":"2","Parch":"2","Ticket":"PC 17608","Fare":"262.375","Cabin":"B57 B59 B63 B66","Embarked":"C"},
    {"PassengerId":"957","Pclass":"2","Name":"Corey, Mrs. Percy C (Mary Phyllis Elizabeth Miller)","Sex":"female","Age":"","SibSp":"0","Parch":"0","Ticket":"F.C.C. 13534","Fare":"21","Cabin":"","Embarked":"S"},
    {"PassengerId":"958","Pclass":"3","Name":"Burns, Miss. Mary Delia","Sex":"female","Age":"18","SibSp":"0","Parch":"0","Ticket":"330963","Fare":"7.8792","Cabin":"","Embarked":"Q"},
    {"PassengerId":"959","Pclass":"1","Name":"Moore, Mr. Clarence Bloomfield","Sex":"male","Age":"47","SibSp":"0","Parch":"0","Ticket":"113796","Fare":"42.4","Cabin":"","Embarked":"S"},
    {"PassengerId":"960","Pclass":"1","Name":"Tucker, Mr. Gilbert Milligan Jr","Sex":"male","Age":"31","SibSp":"0","Parch":"0","Ticket":"2543","Fare":"28.5375","Cabin":"C53","Embarked":"C"},
    {"PassengerId":"961","Pclass":"1","Name":"Fortune, Mrs. Mark (Mary McDougald)","Sex":"female","Age":"60","SibSp":"1","Parch":"4","Ticket":"19950","Fare":"263","Cabin":"C23 C25 C27","Embarked":"S"},
    {"PassengerId":"962","Pclass":"3","Name":"Mulvihill, Miss. Bertha E","Sex":"female","Age":"24","SibSp":"0","Parch":"0","Ticket":"382653","Fare":"7.75","Cabin":"","Embarked":"Q"},
    {"PassengerId":"963","Pclass":"3","Name":"Minkoff, Mr. Lazar","Sex":"male","Age":"21","SibSp":"0","Parch":"0","Ticket":"349211","Fare":"7.8958","Cabin":"","Embarked":"S"},
    {"PassengerId":"964","Pclass":"3","Name":"Nieminen, Miss. Manta Josefina","Sex":"female","Age":"29","SibSp":"0","Parch":"0","Ticket":"3101297","Fare":"7.925","Cabin":"","Embarked":"S"},
    {"PassengerId":"965","Pclass":"1","Name":"Ovies y Rodriguez, Mr. Servando","Sex":"male","Age":"28.5","SibSp":"0","Parch":"0","Ticket":"PC 17562","Fare":"27.7208","Cabin":"D43","Embarked":"C"},
    {"PassengerId":"966","Pclass":"1","Name":"Geiger, Miss. Amalie","Sex":"female","Age":"35","SibSp":"0","Parch":"0","Ticket":"113503","Fare":"211.5","Cabin":"C130","Embarked":"C"},
    {"PassengerId":"967","Pclass":"1","Name":"Keeping, Mr. Edwin","Sex":"male","Age":"32.5","SibSp":"0","Parch":"0","Ticket":"113503","Fare":"211.5","Cabin":"C132","Embarked":"C"},
    {"PassengerId":"968","Pclass":"3","Name":"Miles, Mr. Frank","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"359306","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"969","Pclass":"1","Name":"Cornell, Mrs. Robert Clifford (Malvina Helen Lamson)","Sex":"female","Age":"55","SibSp":"2","Parch":"0","Ticket":"11770","Fare":"25.7","Cabin":"C101","Embarked":"S"},
    {"PassengerId":"970","Pclass":"2","Name":"Aldworth, Mr. Charles Augustus","Sex":"male","Age":"30","SibSp":"0","Parch":"0","Ticket":"248744","Fare":"13","Cabin":"","Embarked":"S"},
    {"PassengerId":"971","Pclass":"3","Name":"Doyle, Miss. Elizabeth","Sex":"female","Age":"24","SibSp":"0","Parch":"0","Ticket":"368702","Fare":"7.75","Cabin":"","Embarked":"Q"},
    {"PassengerId":"972","Pclass":"3","Name":"Boulos, Master. Akar","Sex":"male","Age":"6","SibSp":"1","Parch":"1","Ticket":"2678","Fare":"15.2458","Cabin":"","Embarked":"C"},
    {"PassengerId":"973","Pclass":"1","Name":"Straus, Mr. Isidor","Sex":"male","Age":"67","SibSp":"1","Parch":"0","Ticket":"PC 17483","Fare":"221.7792","Cabin":"C55 C57","Embarked":"S"},
    {"PassengerId":"974","Pclass":"1","Name":"Case, Mr. Howard Brown","Sex":"male","Age":"49","SibSp":"0","Parch":"0","Ticket":"19924","Fare":"26","Cabin":"","Embarked":"S"},
    {"PassengerId":"975","Pclass":"3","Name":"Demetri, Mr. Marinko","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"349238","Fare":"7.8958","Cabin":"","Embarked":"S"},
    {"PassengerId":"976","Pclass":"2","Name":"Lamb, Mr. John Joseph","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"240261","Fare":"10.7083","Cabin":"","Embarked":"Q"},
    {"PassengerId":"977","Pclass":"3","Name":"Khalil, Mr. Betros","Sex":"male","Age":"","SibSp":"1","Parch":"0","Ticket":"2660","Fare":"14.4542","Cabin":"","Embarked":"C"},
    {"PassengerId":"978","Pclass":"3","Name":"Barry, Miss. Julia","Sex":"female","Age":"27","SibSp":"0","Parch":"0","Ticket":"330844","Fare":"7.8792","Cabin":"","Embarked":"Q"},
    {"PassengerId":"979","Pclass":"3","Name":"Badman, Miss. Emily Louisa","Sex":"female","Age":"18","SibSp":"0","Parch":"0","Ticket":"A/4 31416","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"980","Pclass":"3","Name":"O'Donoghue, Ms. Bridget","Sex":"female","Age":"","SibSp":"0","Parch":"0","Ticket":"364856","Fare":"7.75","Cabin":"","Embarked":"Q"},
    {"PassengerId":"981","Pclass":"2","Name":"Wells, Master. Ralph Lester","Sex":"male","Age":"2","SibSp":"1","Parch":"1","Ticket":"29103","Fare":"23","Cabin":"","Embarked":"S"},
    {"PassengerId":"982","Pclass":"3","Name":"Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judith Andersson)","Sex":"female","Age":"22","SibSp":"1","Parch":"0","Ticket":"347072","Fare":"13.9","Cabin":"","Embarked":"S"},
    {"PassengerId":"983","Pclass":"3","Name":"Pedersen, Mr. Olaf","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"345498","Fare":"7.775","Cabin":"","Embarked":"S"},
    {"PassengerId":"984","Pclass":"1","Name":"Davidson, Mrs. Thornton (Orian Hays)","Sex":"female","Age":"27","SibSp":"1","Parch":"2","Ticket":"F.C. 12750","Fare":"52","Cabin":"B71","Embarked":"S"},
    {"PassengerId":"985","Pclass":"3","Name":"Guest, Mr. Robert","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"376563","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"986","Pclass":"1","Name":"Birnbaum, Mr. Jakob","Sex":"male","Age":"25","SibSp":"0","Parch":"0","Ticket":"13905","Fare":"26","Cabin":"","Embarked":"C"},
    {"PassengerId":"987","Pclass":"3","Name":"Tenglin, Mr. Gunnar Isidor","Sex":"male","Age":"25","SibSp":"0","Parch":"0","Ticket":"350033","Fare":"7.7958","Cabin":"","Embarked":"S"},
    {"PassengerId":"988","Pclass":"1","Name":"Cavendish, Mrs. Tyrell William (Julia Florence Siegel)","Sex":"female","Age":"76","SibSp":"1","Parch":"0","Ticket":"19877","Fare":"78.85","Cabin":"C46","Embarked":"S"},
    {"PassengerId":"989","Pclass":"3","Name":"Makinen, Mr. Kalle Edvard","Sex":"male","Age":"29","SibSp":"0","Parch":"0","Ticket":"STON/O 2. 3101268","Fare":"7.925","Cabin":"","Embarked":"S"},
    {"PassengerId":"990","Pclass":"3","Name":"Braf, Miss. Elin Ester Maria","Sex":"female","Age":"20","SibSp":"0","Parch":"0","Ticket":"347471","Fare":"7.8542","Cabin":"","Embarked":"S"},
    {"PassengerId":"991","Pclass":"3","Name":"Nancarrow, Mr. William Henry","Sex":"male","Age":"33","SibSp":"0","Parch":"0","Ticket":"A./5. 3338","Fare":"8.05","Cabin":"","Embarked":"S"},
    {"PassengerId":"992","Pclass":"1","Name":"Stengel, Mrs. Charles Emil Henry (Annie May Morris)","Sex":"female","Age":"43","SibSp":"1","Parch":"0","Ticket":"11778","Fare":"55.4417","Cabin":"C116","Embarked":"C"},
    {"PassengerId":"993","Pclass":"2","Name":"Weisz, Mr. Leopold","Sex":"male","Age":"27","SibSp":"1","Parch":"0","Ticket":"228414","Fare":"26","Cabin":"","Embarked":"S"},
    {"PassengerId":"994","Pclass":"3","Name":"Foley, Mr. William","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"365235","Fare":"7.75","Cabin":"","Embarked":"Q"},
    {"PassengerId":"995","Pclass":"3","Name":"Johansson Palmquist, Mr. Oskar Leander","Sex":"male","Age":"26","SibSp":"0","Parch":"0","Ticket":"347070","Fare":"7.775","Cabin":"","Embarked":"S"},
    {"PassengerId":"996","Pclass":"3","Name":"Thomas, Mrs. Alexander (Thamine Thelma","Sex":"female","Age":"16","SibSp":"1","Parch":"1","Ticket":"2625","Fare":"8.5167","Cabin":"","Embarked":"C"},
    {"PassengerId":"997","Pclass":"3","Name":"Holthen, Mr. Johan Martin","Sex":"male","Age":"28","SibSp":"0","Parch":"0","Ticket":"C 4001","Fare":"22.525","Cabin":"","Embarked":"S"},
    {"PassengerId":"998","Pclass":"3","Name":"Buckley, Mr. Daniel","Sex":"male","Age":"21","SibSp":"0","Parch":"0","Ticket":"330920","Fare":"7.8208","Cabin":"","Embarked":"Q"},
    {"PassengerId":"999","Pclass":"3","Name":"Ryan, Mr. Edward","Sex":"male","Age":"","SibSp":"0","Parch":"0","Ticket":"383162","Fare":"7.75","Cabin":"","Embarked":"Q"},
    ]