server:
  port: 3001
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
  application:
    name: livy-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s

livyAddr: 10.105.222.90:8998,10.105.222.91:8998,10.105.222.92:8998,10.105.222.93:8998
livyNewSessionJars: hdfs:///livy_jars/scalaj-http_2.10-2.0.0.jar
livyNewSessionKind: spark
numExecutors: 1
executorCores: 1